services:
  - type: web
    plan: free
    name: TechMagazineAutoFilterBot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 bot.py
    repo: https://github.com/itsyogieu/TechMagazineAutoFilterBot.git      
    branch: master
    envVars:
      - key: BOT_TOKEN 
        sync: true
      - key: API_ID 
        sync: true
      - key: API_HASH
        sync: true
      - key: ADMINS
        sync: true
      - key: DATABASE_NAME
        sync: true
      - key: DATABASE_URI
        sync: true 
      - key: PICS
        sync: true
      - key: LOG_CHANNEL
        sync: true   
    autoDeploy: true 
